#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
case $1 in
build|-build)
	javac -Xlint -Xlint:-serial uk/co/petertribble/life/*.java
	jar -cmf life.manifest life.jar uk/co/petertribble/life/*.class pixmaps/pctlife.png
	rm uk/co/petertribble/life/*.class
	exit 0
	;;
javadoc|-javadoc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -Xdoclint:all -d javadoc uk.co.petertribble.life
	exit 0
	;;
package|-package)
	./pkg/mkproto > pp
	pkgmk -d /tmp -f pp -r `pwd` TRIBpctlife
	pkgtrans -s /tmp /tmp/TRIBpctlife.pkg TRIBpctlife
	rm pp
	cd /tmp || exit 1
	if [ -x ${THOME}/build/create_zap_from_pkg ]; then
	    ${THOME}/build/create_zap_from_pkg TRIBpctlife /tmp/TRIBpctlife.pkg
	else
	    zip -q -r TRIBpctlife TRIBpctlife
	    mv TRIBpctlife.zip TRIBpctlife.zap
	    ls -l /tmp/TRIBpctlife.pkg /tmp/TRIBpctlife.zap
	fi
	rm -fr /tmp/TRIBpctlife
	exit 0
	;;
pmd|-pmd)
	PMDCATRULES="security bestpractices multithreading"
	RULESETS=""
	shift
	for RULE in $PMDCATRULES "$@"
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=`echo $RULESETS|sed s:,::`
	if [ ! -d ${HOME}/.pmd ]; then
	    mkdir -p ${HOME}/.pmd
	fi
	pmd check --cache ${HOME}/.pmd/cache.pctlife -d uk -R $RULESETS --use-version java-1.8 --aux-classpath `echo lib/java/* | sed 's= =:=g'` 2>/dev/null
	exit 0
	;;
esac
# Flags:
# -b board size (default 128)
# -g cell gap (default 1)
# -s cell size (default 5)
exec java -jar life.jar "$@"
