#!/bin/sh
case $1 in
'-build')
	javac -Xlint -Xlint:-serial uk/co/petertribble/life/*.java
	jar -cmf life.manifest life.jar uk/co/petertribble/life/*.class pixmaps/pctlife.png
	rm uk/co/petertribble/life/*.class
	exit 0
	;;
'-package')
	./pkg/mkproto > pp
	pkgmk -d /tmp -f pp -r `pwd` TRIBpctlife
	pkgtrans -s /tmp /tmp/TRIBpctlife.pkg TRIBpctlife
	rm pp
	cd /tmp
	if [ -x ${THOME}/build/create_zap_from_pkg ]; then
	    ${THOME}/build/create_zap_from_pkg TRIBpctlife /tmp/TRIBpctlife.pkg
	else
	    zip -q -r TRIBpctlife TRIBpctlife
	    mv TRIBpctlife.zip TRIBpctlife.zap
	    ls -l /tmp/TRIBpctlife.pkg /tmp/TRIBpctlife.zap
	fi
	rm -fr /tmp/TRIBpctlife
	exit 0
	;;
'-pmd')
	PMDRULES="basic braces clone empty finalizers imports migrating strictexception strings sunsecure typeresolution unnecessary unusedcode"
	PMDCATRULES="security"
	RULESETS=""
	for RULE in $PMDRULES
	do
	    RULESETS="${RULESETS},rulesets/java/${RULE}.xml"
	done
	for RULE in $PMDCATRULES
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=`echo $RULESETS|sed s:,::`
	pmd -d uk -R $RULESETS -version 1.8 -auxclasspath `echo lib/java/* | sed 's= =:=g'` 2>/dev/null
	exit 0
	;;
esac
exec java -jar life.jar $*
