version = 1

[[annotations]]
path = [ "README.md", "life.jar", "life.manifest", "pixmaps/pctlife.png", "pkg/pkginfo" ]
SPDX-FileCopyrightText = "2025 Peter Tribble"
SPDX-License-Identifier = "CDDL-1.0"
