#!/bin/sh
#
# generate a prototype file for input to pkgmk
#
# feed to pkgmk like so:
#  pkgmk -d /tmp -f tt -r `pwd` TRIBpctlife
#
JARDIR=usr/share/pctlife
OWNER="root bin"
SYSOWNER="root sys"

echo "i pkginfo=./pkg/pkginfo"
echo "i postinstall=./pkg/postinstall"
echo "i postremove=./pkg/postinstall"
echo "f none /usr/bin/pctlife=pkg/life.installed 0755 ${OWNER}"
echo "d none /usr/share 0755 ${SYSOWNER}"
echo "d none /usr/share/applications 0755 root other"
echo "d none /usr/share/pixmaps 0755 root other"
echo "d none /usr/share/pctlife 0755 ${OWNER}"
echo "f none /usr/share/pctlife/README=README 0755 ${OWNER}"
echo "f none /usr/share/pctlife/life.jar=life.jar 0755 ${OWNER}"
echo "f none /usr/share/pixmaps/pctlife.png=pixmaps/pctlife.png 0755 ${OWNER}"
echo "f none /usr/share/applications/pctlife.desktop=pctlife.desktop 0755 ${OWNER}"
